ALTER TABLE clientsCourseWork DROP PASSWORD_FIELD;
ALTER TABLE clientsCourseWork ADD COLUMN PASSWORD_FIELD VARCHAR(255) AFTER EMAIL;
ALTER TABLE clientsCourseWork ADD COLUMN LOGIN VARCHAR(255) AFTER EMAIL;
SELECT * FROM clientsCourseWork;
DELETE FROM clientsCourseWork WHERE ID=1 OR ID=2 OR ID=3 OR ID=4 OR ID=5 OR ID=6 OR ID=7 OR ID=8 OR ID=9 OR ID=10 OR ID=11 OR ID=12;
ALTER TABLE clientsCourseWork AUTO_INCREMENT = 1;