USE clientsCourseWork;
SELECT * FROM clientscoursework;
ALTER TABLE clientsCourseWork DROP PASSWORD_FIELD;
ALTER TABLE clientsCourseWork ADD COLUMN PASSWORD_FIELD VARCHAR(40) NOT NULL AFTER EMAIL;
INSERT INTO clientscoursework (EMAIL, PASSWORD_FIELD) VALUES ('123@yandex.ru', '123');
DELETE FROM clientscoursework WHERE  ID=1 OR ID=2 OR ID=3 OR ID=4 OR ID=5 OR ID=6 OR ID=7 OR ID=8 OR ID=9 OR ID=10;